name: Manual Quality Control (against real devices)

on:
  workflow_dispatch:
    inputs:
      client_version:
        description: 'Client version to check'
        required: true
        type: string

jobs:
  manual-qc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Manual QC script
        env:
          SCREENLY_API_TOKEN: ${{ secrets.SCREENLY_API_TOKEN }}
        run: |
          python -u manual_quality_control.py --client-version ${{ inputs.client_version }}